// languages.js - Complete language data file
const languageData = {
    en: {
        // Navigation
        home: "Home",
        about: "About Me",
        contact: "Contact",
        sendMessages: "Send Messages",
        
        // Home Page
        homeTitle: "My Personal Website - Home",
        welcomeTitle: "Welcome to My Personal Website",
        welcomeSubtitle: "This is my first website that I built myself. I'm learning and developing my skills in web design and development",
        discoverFeatures: "Discover Features",
        getToKnowMe: "Get to Know Me",
        siteFeatures: "Website Features",
        modernDesign: "Modern Design",
        modernDesignDesc: "Responsive design that works on all devices with a modern and attractive look",
        fastPerformance: "Fast Performance",
        fastPerformanceDesc: "Fast loading of sections and images with performance optimization",
        easyToModify: "Easy to Modify",
        easyToModifyDesc: "Clean code that is easy to modify and add to",
        fullyInteractive: "Fully Interactive",
        fullyInteractiveDesc: "Interactions and effects that make the website alive",
        websiteStats: "Website Statistics",
        visitors: "Visitors",
        pages: "Pages",
        featuresCount: "Features",
        days: "Days",
        aboutInfo: "About Me Info",
        contactMe: "Contact Me",
        myProjects: "My Projects",
        latestUpdates: "Latest Updates",
        websiteCreated: "Website fully created",
        pagesAdded: "Added 'About Me' and 'Contact' pages",
        responsiveDesign: "Responsive design for all screens",
        blogSoon: "Adding blog soon",
        footerTitle: "My Personal Website",
        footerSubtitle: "My first website - A web development learning journey",
        developedWithHeart: "© 2024 My Personal Website | Developed with ❤",
        changeColor: "Change Color",
        welcomeBtn: "Welcome",
        
        // About Page
        aboutTitle: "About Me - My Personal Website",
        whoAmI: "About Me",
        greeting: "Hello! I'm a beginner web developer learning and improving my skills",
        aboutMe: "About Me",
        passion: "I'm passionate about web technology and self-learning. I started my programming journey recently and I'm working on developing my skills in:",
        goals: "My Goals",
        goal1: "Master web development basics",
        goal2: "Build practical projects",
        goal3: "Learn React.js",
        goal4: "Create a portfolio",
        goal5: "Contribute to open source projects",
        plan: "My Plan",
        month1: "First Month",
        month1Task1: "HTML, CSS basics",
        month1Task2: "Build personal website",
        month2: "Second Month",
        month2Task1: "JavaScript basics",
        month2Task2: "Add interactivity to website",
        month3: "Third Month",
        month3Task1: "Node.js basics",
        month3Task2: "Build simple applications",
        backToHome: "← Back to Home",
        allRightsReserved: "© 2024 My Personal Website | All rights reserved",
        
        // Skills
        html: "HTML",
        css: "CSS",
        javascript: "JavaScript",
        vscode: "VS Code",
        git: "Git",
        nodejs: "Node.js",
        
        // Contact Page
        contactTitle: "Contact Me - Integrated Sending System",
        smartSendingSystem: "Smart Sending System",
        sendOnceMessage: "Send your message once, it reaches both email and Telegram!",
        email: "Email",
        emailDescription: "Direct sending via Formspree",
        telegramBot: "Telegram Bot",
        telegramDescription: "Instant notification on Telegram",
        checkingBotStatus: "Checking bot status...",
        integratedSendingSystem: "Integrated Sending System",
        integratedSendingForm: "Integrated Sending Form",
        formDescription: "Fill out the form and send. Your message will reach both my email and Telegram immediately",
        fullName: "Full Name",
        namePlaceholder: "Enter your full name",
        emailAddress: "Email Address",
        emailPlaceholder: "example@email.com",
        phoneNumber: "Phone Number",
        phonePlaceholder: "05XXXXXXXX",
        messageType: "Message Type",
        selectMessageType: "Select message type",
        inquiry: "Inquiry",
        collaboration: "Collaboration Request",
        interview: "Job Interview",
        complaint: "Complaint or Suggestion",
        other: "Other",
        message: "Message",
        messagePlaceholder: "Write your message in detail here...",
        sendMessage: "Send Message",
        sending: "Sending...",
        step1: "Write Message",
        step2: "Send Data",
        step3: "Confirm Sending",
        sendingResults: "Sending Results",
        emailStatus: "Email:",
        telegramStatus: "Telegram Bot:",
        waitingForSending: "Waiting for sending...",
        sentSuccessfully: "Sent successfully",
        sendingFailed: "Sending failed",
        messageReceived: "✅ Your message has been received!",
        receivedBoth: "Reached both email and Telegram",
        receivedEmail: "Reached email",
        receivedTelegram: "Reached Telegram",
        sendingFailedMessage: "❌ Failed to send message. Please try again.",
        fillRequiredFields: "❌ Please fill all required fields",
        validEmail: "❌ Please enter a valid email address",
        footerRights: "© 2024 Integrated Sending System | All rights reserved",
        
        // Bot Status Messages
        checkingBot: "Checking bot...",
        botActive: "Bot active:",
        botError: "Bot error:",
        connectionError: "Connection error with bot",
        systemReady: "System ready for sending",
        
        // System Messages
        systemTime: "Time: ",
        formspreeAPI: "Formspree API",
        telegramAPI: "Telegram Bot API",
        testMessage: "Test System",
        testMessageDesc: "Send a test message to verify system operation",
        
        // Today's Date
        today: "Today: "
    },
    
    ar: {
        // Navigation
        home: "الرئيسية",
        about: "من أنا",
        contact: "اتصل بي",
        sendMessages: "إرسال الرسائل",
        
        // Home Page
        homeTitle: "موقعي الشخصي - الرئيسية",
        welcomeTitle: "مرحباً بكم في موقعي الشخصي",
        welcomeSubtitle: "هذا هو موقعي الأول الذي بنيته بنفسي. أتعلم وأطور مهاراتي في تصميم وتطوير الويب",
        discoverFeatures: "اكتشف المميزات",
        getToKnowMe: "تعرف علي",
        siteFeatures: "مميزات الموقع",
        modernDesign: "تصميم عصري",
        modernDesignDesc: "تصميم متجاوب يعمل على جميع الأجهزة بمظهر حديث وجذاب",
        fastPerformance: "أداء سريع",
        fastPerformanceDesc: "تحميل سريع للأقسام والصور مع تحسين للأداء",
        easyToModify: "سهل التعديل",
        easyToModifyDesc: "كود نظيف وسهل التعديل والإضافة عليه",
        fullyInteractive: "متحرك بالكامل",
        fullyInteractiveDesc: "تفاعلات وتأثيرات تجعل الموقع حياً",
        websiteStats: "إحصائيات الموقع",
        visitors: "زائر",
        pages: "صفحة",
        featuresCount: "ميزة",
        days: "يوم",
        aboutInfo: "معلومات عني",
        contactMe: "تواصل معي",
        myProjects: "مشاريعي",
        latestUpdates: "آخر التحديثات",
        websiteCreated: "تم إنشاء الموقع بالكامل",
        pagesAdded: "إضافة صفحات 'من أنا' و 'اتصل بي'",
        responsiveDesign: "تصميم متجاوب لجميع الشاشات",
        blogSoon: "إضافة مدونة قريباً",
        footerTitle: "موقعي الشخصي",
        footerSubtitle: "أول موقع لي - رحلة تعلم تطوير الويب",
        developedWithHeart: "© 2024 موقعي الشخصي | تم التطوير بـ ❤",
        changeColor: "تغيير اللون",
        welcomeBtn: "ترحيب",
        
        // About Page
        aboutTitle: "من أنا - موقعي الشخصي",
        whoAmI: "من أنا",
        greeting: "مرحباً! أنا مطور ويب مبتدئ أتعلم وأطور مهاراتي",
        aboutMe: "عني",
        passion: "أنا شغوف بتكنولوجيا الويب والتعلم الذاتي. بدأت رحلتي في البرمجة مؤخراً وأعمل على تطوير مهاراتي في:",
        goals: "أهدافي",
        goal1: "إتقان أساسيات تطوير الويب",
        goal2: "بناء مشاريع عملية",
        goal3: "تعلم React.js",
        goal4: "إنشاء محفظة أعمال",
        goal5: "المساهمة في مشاريع مفتوحة المصدر",
        plan: "خطتي",
        month1: "الشهر الأول",
        month1Task1: "HTML, CSS أساسيات",
        month1Task2: "بناء موقع شخصي",
        month2: "الشهر الثاني",
        month2Task1: "JavaScript أساسيات",
        month2Task2: "إضافة تفاعل للموقع",
        month3: "الشهر الثالث",
        month3Task1: "Node.js أساسيات",
        month3Task2: "بناء تطبيقات بسيطة",
        backToHome: "← العودة للرئيسية",
        allRightsReserved: "© 2024 موقعي الشخصي | جميع الحقوق محفوظة",
        
        // Skills
        html: "HTML",
        css: "CSS",
        javascript: "JavaScript",
        vscode: "VS Code",
        git: "Git",
        nodejs: "Node.js",
        
        // Contact Page
        contactTitle: "اتصل بي - نظام الإرسال المتكامل",
        smartSendingSystem: "نظام الإرسال الذكي",
        sendOnceMessage: "أرسل رسالتك مرة واحدة، تصل إلى البريد الإلكتروني والتليجرام معاً!",
        email: "البريد الإلكتروني",
        emailDescription: "إرسال مباشر عبر Formspree",
        telegramBot: "تيليجرام بوت",
        telegramDescription: "إشعار فوري على تليجرام",
        checkingBotStatus: "جارِ التحقق من حالة البوت...",
        integratedSendingSystem: "نظام الإرسال المتكامل",
        integratedSendingForm: "نموذج الإرسال المتكامل",
        formDescription: "املأ النموذج وأرسل. ستصل رسالتك إلى بريدي الإلكتروني وإلى تليجرام فوراً",
        fullName: "الاسم الكامل",
        namePlaceholder: "أدخل اسمك الثلاثي",
        emailAddress: "البريد الإلكتروني",
        emailPlaceholder: "example@email.com",
        phoneNumber: "رقم الهاتف",
        phonePlaceholder: "05XXXXXXXX",
        messageType: "نوع الرسالة",
        selectMessageType: "اختر نوع الرسالة",
        inquiry: "استفسار",
        collaboration: "طلب تعاون",
        interview: "مقابلة عمل",
        complaint: "شكوى أو اقتراح",
        other: "أخرى",
        message: "الرسالة",
        messagePlaceholder: "اكتب رسالتك هنا بتفصيل...",
        sendMessage: "إرسال الرسالة",
        sending: "جاري الإرسال...",
        step1: "اكتب الرسالة",
        step2: "إرسال البيانات",
        step3: "تأكيد الإرسال",
        sendingResults: "نتائج الإرسال",
        emailStatus: "البريد الإلكتروني:",
        telegramStatus: "تيليجرام بوت:",
        waitingForSending: "في انتظار الإرسال...",
        sentSuccessfully: "تم الإرسال بنجاح",
        sendingFailed: "فشل الإرسال",
        messageReceived: "✅ تم استلام رسالتك!",
        receivedBoth: "وصلت إلى البريد وتيجرام",
        receivedEmail: "وصلت إلى البريد",
        receivedTelegram: "وصلت إلى تيليجرام",
        sendingFailedMessage: "❌ فشل إرسال الرسالة. حاول مرة أخرى.",
        fillRequiredFields: "❌ يرجى ملء جميع الحقول المطلوبة",
        validEmail: "❌ يرجى إدخال بريد إلكتروني صحيح",
        footerRights: "© 2024 نظام الإرسال المتكامل | جميع الحقوق محفوظة",
        
        // Bot Status Messages
        checkingBot: "جارِ التحقق من البوت...",
        botActive: "البوت نشط:",
        botError: "خطأ في البوت:",
        connectionError: "خطأ في الاتصال بالبوت",
        systemReady: "النظام جاهز للإرسال",
        
        // System Messages
        systemTime: "الوقت: ",
        formspreeAPI: "Formspree API",
        telegramAPI: "Telegram Bot API",
        testMessage: "اختبار النظام",
        testMessageDesc: "إرسال رسالة اختبار للتأكد من عمل النظام",
        
        // Today's Date
        today: "اليوم: "
    }
};